### ISSUE TITLE
EVERY FPS GAME

### ISSUE THREAD

**Issue by ipetloudog** [ayufan/steam-deck-tools#27] opened 2022-12-17 13:41 UTC
Every FPS GAME since the beginning of time uses holding start to check the scoreboard. Makes game unplayable due to changing profile in tools.

**Comment by ayufan** [comment] 2022-12-17 13:49
Duplicate of https://github.com/ayufan/steam-deck-tools/issues/22

**Closed by ayufan** 2022-12-17 13:49 UTC
