### ISSUE TITLE
When the power control is turned on, the volume bar and brightness bar are not displayed

### ISSUE THREAD

**Issue by CWBOBO** [ayufan/steam-deck-tools#74] opened 2023-02-17 10:05 UTC
When the power control is turned on, the volume bar and brightness bar are not displayed

**Comment by SpazShark** [comment] 2023-02-24 15:04
I noticed that my volume bar vanished as well but didn't try stopping power control. Would love it if this could be addressed.

**Comment by ayufan** [comment] 2023-02-24 15:06
Duplicate of: https://github.com/ayufan/steam-deck-tools/issues/60

**Closed by ayufan** 2023-02-24 15:06 UTC
